services:
  - type: web
    name: email-generator-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: "https://your-go-frontend-url.onrender.com, http://localhost:8080"